# Use LOG_LEVEL: debug to print all requests on the console
#LOG_LEVEL: debug
server:
  port: 3000
logging:
  root_logger_name: simple-node-app
  human_readable: false
external_service: http://127.0.0.1:3048

