replicaCount: 1

image:
  repository: rplan/simple-node-app
  tag: latest

podLabels: {}

serviceLabels: {}

resources:
  requests:
    cpu: 250m
    memory: 128Mi

config:
  LOG_LEVEL: debug
  external_service:

service:
  type: ClusterIP
  port: 80
  annotations: {}
  name: simple-node-app

podAnnotations: {}
